### ISSUE TITLE
Support for custom smart vent device handler

### ISSUE THREAD

**Issue by jope2000** [SANdood/Ecobee-Suite#13]
Hi

I have been using the Ecobee-Suite in combination with my Keen Smart Vents for a while now and it's generally working great.
The only unexpected behaviour I have run into so far, is that custom device handlers (DH) for Keen Smart Vents are not recognized by the Smart Vent app. E.g. https://github.com/constjs/jcdevhandlers/blob/master/devicetypes/jscgs350/my-keen-home-smart-vent-v2.src/my-keen-home-smart-vent-v2.groovy

The main reason why I want to use a custom DH is to make the vents less chatty. 
I looked at the implementation of the SmartVents app to understand why it's not recognizing it. The main thing seems to be that the "device.keenHomeSmartVent" type isn't valid for customer DH.

Is there a particular reason why the inputs for the smart vent selection is limit to this particular type? The rest of the code seems to treat both the Econet and Keen vent equivalently.

Thanks,
Jope

**Comment by SANdood** [comment]
The only reason for using the specific device names in the selector is because the “generic” capability for these is “dimmer”, which can be confusing (and a LONG list of devices to choose from). 3rd party DTHs are rarely named in a manner that allows them to be specified in this manner (because of the somewhat odd naming restrictions imposed by SmartThings).

Feel free to edit your copy of the Smart Vent Helper and change “device.keenHomeSmartVent” to “capability.dimmer”, and you should be able to select your vents from that list.

Thanks!
       Barry

**Comment by jope2000** [comment]
Makes sense.
Thanks for the quick feedback.
