### ISSUE TITLE
Smartthings DTH UX

### ISSUE THREAD

**Issue by arcegabriel** [SANdood/Ecobee-Suite#16]
It will be awesome if the DTH made it easy to:
1. Differentiate UX elements that show state versus action
2. On an action & state UX element, make it clear action versus state (Fan is off, action will turn it to circulate)
3. On an action button show transition states. Fan is on but will turn off momentarily (the furnace may take a few seconds to do this - sometimes longer)

**Comment by SANdood** [comment]
Excellent suggestions, as I am always trying to improve the UI.

Unfortunately, on SmartThings Classic, I have pretty much hit the wall on what the platform will allow me to do. If you have some specific suggestions, or an example or two, I'll be happy to entertain further improvements.

That said, SmartThings has made it clear that they intend to deprecate SmartThings Classic "soon." The new Samsung app affords exactly ZERO ability to customize the UI, so whatever least-common-denominator features they choose to support is pretty much it - nothing anyone can do about it, at least until (and if) they release a developer API for their new mobile platform (don't hold your breath).

Alas, all this leads me to begin the arduous move to Hubitat, in hopes that their (future) UI affords a better environment for customization.

But as I said, if you have some specific suggestions where I could improve things, please do let me know.

**Comment by arcegabriel** [comment]
From what I can see in other situation (schlage lock). They have 3 icons:
1. State: Locked 
2. Action 1: Lock
3. Action 2: Unlock

Another idea from ecobee Control for state: Right Now: Off. Maybe if there is an action there should be an arrow to indicate it is an action
But I can not say I love their UX anyway...

**Comment by SANdood** [comment]
Give the Ecobee Suite UI a couple of days - most of the buttons that do anything do in fact show you when they are waiting, but I have tried very hard to hide most delays so that it feels more responses. 

FWIW, the icons on the white background ABOVE the word "Command Center" don't do anything - they display a state. The ones BELOW that are almost all active. Due to an inherited indiosyncracy, some functions have more than one way to change them - you can tap the FAN AUTO button down below the sliders, or you can cycle through fan modes by clicking the Fan icon just under Command Center.
Action buttons that don't work in a particular situation are greyed out, by the way, so that you can't "resume program" unless there is a Hold override underway.

I know it isn't pretty, but it's better than most all other thermostat implementations on SmartThings (if I do say so myself - and I do).

Enjoy!!!

**Comment by arcegabriel** [comment]
Thanks, will do. I've been squeezing looking at this after work and in between kids activities (so haven't spent a good amount of time). I will give some time over the weekend to get more familiar.
