### ISSUE TITLE
Hubitat: Smart Vents & Switches - Unable to complete setup - Ecobee Suite Thermostat Integration - Empty 

### ISSUE THREAD

**Issue by Dannyzen** [SANdood/Ecobee-Suite#28]
I'm attempting to use the Smart Vents & Switches app. 

During the setup process I'm unable to select thermostats in the "Ecobee Suite Thermostat Integration" Section. (I have several virtual and physical thermostats but they do not populate) 

UI Screenshot: 
![Screenshot from 2020-01-24 13-56-48](https://user-images.githubusercontent.com/659908/73095821-69009200-3eb1-11ea-9301-e040d856a6f6.png)

Attempting in Chromium & Firefox

Happy to supply more info. Just let me know.

**Comment by SANdood** [comment]
Have you installed the entire Ecobee Suite?

All of the Ecobee Suite Helper apps work ONLY with Ecobee Suite Thermostat devices - if you don't have any of those, you won't be able to complete the setup (by design).

Also, the Suite is dependent upon the Parent/Child structure - Ecobee Suite Manager is the Parent to each of the ES Thermostats and Sensors, and to all of the Helpers. You can't run the Helper apps independently - they must be created from Ecobee Suite Manager (on Hubitat, you can then edit the Helpers directly from the Apps menu).

**Comment by Dannyzen** [comment]
@SANdood Thanks for taking a look. I have confirmed all apps in the Ecobee Suite have now been installed. 

Looking at my devices, I see line items for devices of type Ecobee Suite Thermostat and I am able to select the appropriate item in the Select Thermostat menu.

Thanks for the guidance!
