### ISSUE TITLE
Resume program not working 

### ISSUE THREAD

**Issue by Porch01** [SANdood/Ecobee-Suite#56]
I have a helper smartapp setup to resume the ecobee program when I return home(I'm back routine runs) but it does not take the ecobee out of away status (away status on the ecobee was set from another routine running in  another helper app).  Any thoughts on what may be causing this?  Thank you.

**Comment by SANdood** [comment]
SmartThings by any chance?

Routines are no longer support by SmartThings, now that the conversion to the new app is complete.

You will need to create a virtual switch that gets turned on when you return (I suggest configuring a momentary switch so that it immediately gets turned back off), and change the Routines/Modes/Switches/Programs Helper to activate when the switch gets turned on...

**Comment by Maksim-us** [comment]
I use "Location mode change" as the trigger for the helper app to set "away", "night", and "resume" and it seems to work.
