### ISSUE TITLE
Smart Humidity use external sensors

### ISSUE THREAD

**Issue by hoveeman** [SANdood/Ecobee-Suite#57]
Feature Request:

I have multiple temperature and humidity sensors throughout my home. It would be great if I could use their humidity level to help adjust the Smart Humidity rule. You could add each one to the rule and it could provide a total average level for the house. My thoughts for this show that throughout my home I have almost a 5% humidity swing, and it would be nice to have an average to represent the house.

**Comment by SANdood** [comment]
A reasonable suggestion, but given the complexity of implementation, I doubt that I will ever implement it. As with using external temperature sensors, it would be both confusing and complicated to figure out (dynamically) the requisite setpoint adjustments required to get the thermostat to add (or stop adding) humidity. FWIW, the code would have to calculate the average vs a target that set externally instead of on the thermostat, then adjust the setpoint relative to what the thermostat thinks is the current humidity levels. And after all that, the humidity will be changed across ALL rooms in the house, likely with no real effect on the differences between rooms (e.g., the humidity in ALL rooms will likely change together).

I have thus long maintained the policy that I won't support external temperature or humidity sensors with my helpers.

Your best bet is to do some manual calculations to figure what (average) thermostat humidity setting works best for your home, then use the Ecobee's Preferences/Thresholds to adjust the thermostat's humidity reading so that it is close to your desired average.
